# Generated by Django 5.0.1 on 2024-02-22 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CV_Profile",
            fields=[
                (
                    "cvID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("profile_img", models.TextField()),
                ("about", models.TextField()),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "userID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=255)),
                ("lastName", models.CharField(max_length=255)),
                ("userName", models.CharField(max_length=255)),
                ("profile_img", models.TextField()),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("userPassword", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "userID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=255)),
                ("lastName", models.CharField(max_length=255)),
                ("userName", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("userPassword", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "educationID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("institution", models.CharField(max_length=255)),
                ("education_course", models.CharField(max_length=255)),
                ("education_start_date", models.DateField()),
                ("education_end_date", models.DateField()),
                (
                    "cvID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.cv_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "objectiveID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("objective_description", models.TextField()),
                (
                    "cvID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.cv_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "projectID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_description", models.TextField()),
                (
                    "cvID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.cv_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "skillID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("skill_level", models.CharField(max_length=255)),
                (
                    "cvID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.cv_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "socialMediaID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("socialMedia_name", models.CharField(max_length=255)),
                ("socialMedia_link", models.CharField(max_length=255)),
                (
                    "cvID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.cv_profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cv_profile",
            name="userID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.student"
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "addressID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("lineOne", models.CharField(max_length=255)),
                ("lineTwo", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("postCode", models.CharField(max_length=255)),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerExperience",
            fields=[
                (
                    "volunteerExperienceID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("volunteer_start_date", models.DateField()),
                ("volunteer_end_date", models.DateField()),
                ("volunteer_description", models.TextField()),
                (
                    "cvID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.cv_profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "workExperienceID",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("job_start_date", models.DateField()),
                ("job_end_date", models.DateField()),
                ("job_description", models.TextField()),
                ("job_address", models.CharField(max_length=255)),
                (
                    "cvID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.cv_profile",
                    ),
                ),
            ],
        ),
    ]
