# Generated by Django 5.0.1 on 2024-02-22 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="address",
            table="Address",
        ),
        migrations.AlterModelTable(
            name="cv_profile",
            table="CV_Profile",
        ),
        migrations.AlterModelTable(
            name="education",
            table="Education",
        ),
        migrations.AlterModelTable(
            name="objective",
            table="Objective",
        ),
        migrations.AlterModelTable(
            name="project",
            table="Project",
        ),
        migrations.AlterModelTable(
            name="recruiter",
            table="Recruiter",
        ),
        migrations.AlterModelTable(
            name="skill",
            table="Skill",
        ),
        migrations.AlterModelTable(
            name="socialmedia",
            table="SocialMedia",
        ),
        migrations.AlterModelTable(
            name="student",
            table="Student",
        ),
        migrations.AlterModelTable(
            name="volunteerexperience",
            table="VolunteerExperience",
        ),
        migrations.AlterModelTable(
            name="workexperience",
            table="WorkExperience",
        ),
    ]
