# Generated by Django 5.0.1 on 2024-02-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_address_table_alter_cv_profile_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="userID",
            field=models.ForeignKey(
                db_column="userID",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.student",
            ),
        ),
    ]
