# Generated by Django 5.0.1 on 2024-02-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_address_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv_profile",
            name="userID",
            field=models.ForeignKey(
                db_column="userID",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.student",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="cvID",
            field=models.ForeignKey(
                db_column="cvID",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.cv_profile",
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="cvID",
            field=models.ForeignKey(
                db_column="cvID",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.cv_profile",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cvID",
            field=models.ForeignKey(
                db_column="cvID",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.cv_profile",
            ),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="userID",
            field=models.CharField(
                db_column="userID", max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="cvID",
            field=models.ForeignKey(
                db_column="cvID",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.cv_profile",
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="cvID",
            field=models.ForeignKey(
                db_column="cvID",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.cv_profile",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerexperience",
            name="cvID",
            field=models.ForeignKey(
                db_column="cvID",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.cv_profile",
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="cvID",
            field=models.ForeignKey(
                db_column="cvID",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.cv_profile",
            ),
        ),
    ]
