# Generated by Django 5.0.1 on 2024-02-22 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_cv_profile_userid_alter_education_cvid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv_profile",
            name="points",
            field=models.IntegerField(
                max_length=255, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
