# Generated by Django 5.0.1 on 2024-02-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_cv_profile_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.DateField(default="2006-01-01"),
        ),
    ]
