# Generated by Django 5.0.1 on 2024-02-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_student_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv_profile",
            name="about",
            field=models.CharField(db_collation="utf8mb4_unicode_ci", max_length=255),
        ),
    ]
