# Generated by Django 5.0.1 on 2024-03-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_cv_profile_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv_profile",
            name="gender",
            field=models.CharField(default="Not Specified", max_length=255),
        ),
    ]
